name: "San Francisco Upper Cervical Chiropractic"
markdown: redcarpet
highlighter: false
exclude: [ Gemfile , Gemfile.lock , CNAME , README.md ]

sass:
  style: :nested

adr:
  street: 4052 18th St
  city: San Francisco
  state: CA
  zip: "94114"
tel:
  areacode: "415"
  prefix: "967"
  suffix: "3177"
email: drprice@sanfranciscouppercervical.com
url: http://sanfranciscouppercervical.com/

defaults:
  readmore: "Read More"